spring:
  application:
    name: HazelCast-Sever
hazelcast:
  loggingType: slf4j
  eventThreadCount: 10
  securityEnable: true
  diagnosticsEnabled: true
  healthDelaySeconds: 60
  healthLogLevel: NOISY
  enableJMX: true
  slowOpDetector: true
  enableREST: false
  enableMemCache: false
  instanceName: HAZELCAST_SERVER
