server:
  port: 8080
spring:
  application:
    name: HazelCast-Sever
  profiles:
    active: dev
logging:
  config: jcp:logback.xml
hazelcast:
  logginType: slf4j
  eventThreadCount: 10
  securityEnable: true
  diagnosticsEnabled: true
  healthDelaySeconds: 60
  healthLogLevel: NOISY
  enableJMX: true
  slowOpDetector: true
  enableREST: false
  enableMemCache: false
  instanceName: HAZELCAST_SERVER
